---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001 
    seccompProfile:
      type: RuntimeDefault
    # imagePullSecrets:
    #  - name: dockerhub 
    containers:
      - image: nginx:latest
        name: nginx 
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false 
            capabilities:
              drop:
              - ALL 
              add:
              - NET_BIND_SERVICE