---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: nginx-simple
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: "nginxdemos/hello"