---
apiVersion: v1
kind: Service
metadata:
  name: ffx-nginx-service
  namespace: ffx-nginx-ns
spec:
  selector:
    app: nginx-simple
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Or NodePort/LoadBalancer depending on your needs