---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: my-fast-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: LoadBalancer # Or NodePort/LoadBalancer depending on your needs